spring:
  datasource:
    username: wang1
    password:
    url: jdbc:mysql://10.63.130.146:3306/signin?useSSL=false&serverTimezone=Asia/Shanghai

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
