spring:
  datasource:
    username: wang1
    password: bit123
    url: jdbc:mysql://10.63.110.16:3306/signin?useSSL=false&serverTimezone=Asia/Shanghai

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://10.62.132.160:5173"
            allowedMethods:
              - GET
